### ISSUE TITLE
请教一些小白问题

### ISSUE THREAD

**Issue by FalAnge1217** [taishan1994/W2NER_predict#1]
大佬，我看了论文和代码，有几个地方没看明白（跨专业小白），希望大佬能解答一下：
第一：条件CLN层的原理？
第二：Distance Embedding，Word Embedding，Region Embedding三个Embedding层是怎么来的，这里还有点没搞明白，dist_inputs得到位置编码dis_emb；grid_mask2d和上三角矩阵得到区域编码reg_embedding，具体的细节还有点迷，特别是dist_inputs这里

希望大佬能解答一下，问了作者没回（我哭了）

**Comment by taishan1994** [comment]
> 大佬，我看了论文和代码，有几个地方没看明白（跨专业小白），希望大佬能解答一下： 第一：条件CLN层的原理？ 第二：Distance Embedding，Word Embedding，Region Embedding三个Embedding层是怎么来的，这里还有点没搞明白，dist_inputs得到位置编码dis_emb；grid_mask2d和上三角矩阵得到区域编码reg_embedding，具体的细节还有点迷，特别是dist_inputs这里
> 
> 希望大佬能解答一下，问了作者没回（我哭了）

具体论文我也没有看额，只是大致了解了一下然后复现了下。你可以去搜别人讲的博客，不过还需要对着代码看，最好找一个数据集然后代码一步一步对着看，这样才能够完全理解。

**Comment by taishan1994** [comment]
> > 大佬，我看了论文和代码，有几个地方没看明白（跨专业小白），希望大佬能解答一下： 第一：条件CLN层的原理？ 第二：Distance Embedding，Word Embedding，Region Embedding三个Embedding层是怎么来的，这里还有点没搞明白，dist_inputs得到位置编码dis_emb；grid_mask2d和上三角矩阵得到区域编码reg_embedding，具体的细节还有点迷，特别是dist_inputs这里
> > 希望大佬能解答一下，问了作者没回（我哭了）
> 
> 具体论文我也没有看额，只是大致了解了一下然后复现了下。你可以去搜别人讲的博客，不过还需要对着代码看，最好找一个数据集然后代码一步一步对着看，这样才能够完全理解。关于三个嵌入层怎么来的，可参考bert的三个嵌入。条件层归一化去搜苏剑林的CLN。
