### ISSUE TITLE
您好，想问下数据预处理

### ISSUE THREAD

**Issue by zweno** [taishan1994/W2NER_predict#2]
有转换这个需要的格式的代码吗

**Comment by taishan1994** [comment]
> 有转换这个需要的格式的代码吗

不知道你指的格式是什么，是数据集的格式么，这个自己转换下就好了。

**Comment by FalAnge1217** [comment]
> > 有转换这个需要的格式的代码吗
> 
> 不知道你指的格式是什么，是数据集的格式么，这个自己转换下就好了。

你好，我想把BIO标注的数据集转换成代码中这种索引表示的数据集，不知道大佬有没有现成的轮子可以分享，邮箱2674053421@qq.com

**Comment by taishan1994** [comment]
> > > 有转换这个需要的格式的代码吗
> > 
> > 
> > 不知道你指的格式是什么，是数据集的格式么，这个自己转换下就好了。
> 
> 你好，我想把BIO标注的数据集转换成代码中这种索引表示的数据集，不知道大佬有没有现成的轮子可以分享，邮箱[2674053421@qq.com](mailto:2674053421@qq.com)

没有额，自己转换下吧，也不是很难。
